spin_manifest_version = 2

[application]
authors = []
description = "Voter UI, admin UI and vote handler edge function"
name = "vote-edge-function"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "vote-edge-function"

[component.vote-edge-function]
source = "dist/vote-edge-function.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = [
  "https://{CDN_HOSTNAME}",
  "https://{ORIGIN_HOSTNAME}"
]

[component.vote-edge-function.build]
command = "npm install && npm run build"
watch = ["src/**/*.js"]